# -*- coding: utf-8 -*-
"""Pre-trained models for text-to-speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1BLUVq3ii15IxQDVTC_LRJud-pjG7qZ
"""

!pip install datasets

from datasets import load_dataset
import torch
from IPython.display import Audio

from transformers import SpeechT5Processor, SpeechT5ForTextToSpeech, SpeechT5HifiGan

processor = SpeechT5Processor.from_pretrained("microsoft/speecht5_tts")
model = SpeechT5ForTextToSpeech.from_pretrained("microsoft/speecht5_tts")

inputs = processor(text="Hello, my dog is cute", return_tensors="pt")

embeddings_dataset = load_dataset("Matthijs/cmu-arctic-xvectors", split="validation")

embeddings_dataset

speaker_embeddings = torch.tensor(embeddings_dataset[16]["xvector"]).unsqueeze(0)

speaker_embeddings.shape

vecoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan")

inputs

speech = model.generate_speech(inputs["input_ids"], speaker_embeddings=speaker_embeddings, vocoder=vecoder)

Audio(speech.numpy(), rate=16000)

"""# Bark"""

from transformers import BarkProcessor, BarkModel

processor = BarkProcessor.from_pretrained("suno/bark")
model = BarkModel.from_pretrained("suno/bark")

inputs = processor(text="♪ Hello, my dog is cute [laughter] ",voice_preset="v2/en_speaker_3")

inputs

speech_output = model.generate(**inputs).cpu()

model.generation_config.sample_rate

Audio(speech_output.numpy(), rate=24000)

"""# VitsModel"""

from transformers import VitsModel, VitsTokenizer

from transformers import VitsModel, VitsTokenizer

model = VitsModel.from_pretrained("facebook/mms-tts-deu")
tokenizer = VitsTokenizer.from_pretrained("facebook/mms-tts-deu")

text_example = (
    "Ich bin Schnappi das kleine Krokodil, komm aus Ägypten das liegt direkt am Nil."
)

inputs = tokenizer(text_example,return_tensors="pt")
with torch.no_grad():
  outputs = model(inputs["input_ids"])

outputs

speech = outputs["waveform"]

Audio(speech, rate=16000)

